### ISSUE TITLE
Particular package builds return 404 error from API when retrieving package details

### ISSUE THREAD

**Issue by GregSloan** [habitat-sh/builder#1121]
### `hab` CLI version
N/A

### Platform Details
Public builder v1 API

### Scenario:
Attempting to sync Habitat packages from public builder to on-prem

### Steps to Reproduce:
Browse to URI for certain package builds
e.g.  https://bldr.habitat.sh/v1/depot/channels/chef/chef-scaffolding-chef-master-habitat-build/pkgs/scaffolding-chef/0.5.0/20190626205325

This build exists and is listed under the parent version:
https://bldr.habitat.sh/v1/depot/channels/chef/chef-scaffolding-chef-master-habitat-build/pkgs/scaffolding-chef/0.5.0

### Expected Result:
return of a JSON object with the package details of that version

### Actual Result:
API returns 404

**Comment by eeyun** [comment]
This is expected behavior. By default this endpoint requires a `?target` query param. If no target is passed into the query then we check the system headers to try to determine the target and if we can't determine via headers the target defaults to linux. I'm investigating whether there is a bug in our header checking code but so far i'm not finding anything out of the ordinary.

In order to work around this, you can build your uri like so:
`https://bldr.habitat.sh/v1/depot/channels/chef/chef-scaffolding-chef-master-habitat-build/pkgs/scaffolding-chef/0.5.0/20190626205325?target=x86-64_windows`

**Comment by gsloan-chef** [comment]
Okay, that makes some sense. Although I just tried the link with ?target=x86-64_windows and it's giving a 422 error instead.

If this is expected behavior than would it makes sense to request the 'target' info to be added to the output from this call: https://bldr.habitat.sh/v1/depot/channels/chef/chef-scaffolding-chef-master-habitat-build/pkgs/scaffolding-chef/0.5.0 ? Otherwise you have to guess the target info before getting the details of a particular build.

**Comment by eeyun** [comment]
>Okay, that makes some sense. Although I just tried the link with ?target=x86-64_windows and it's giving a 422 error instead.
Strange, I can't reproduce that at all. Maybe need to do a hard refresh on that page?

> If this is expected behavior than would it makes sense to request the 'target' info to be added to the output from this call: https://bldr.habitat.sh/v1/depot/channels/chef/chef-scaffolding-chef-master-habitat-build/pkgs/scaffolding-chef/0.5.0 ? Otherwise you have to guess the target info before getting the details of a particular build.

IMO Yes, it absolutely should, and I'm investigating if that's possible. I don't have an answer on the requirement of the target, it seems strange to me as well, I'm not certain why we go that path. It's possible that this is a side effect of something we're doing in the backend. @chefsalim any insight on that?

**Comment by eeyun** [comment]
Ok, I apologize. I do have an answer for you on this _and_ I've got a fix for the channels endpoint inbound later today. The reason we obligate the target in that query is pretty straightforward: while it is very highly unlikely that two builds of the same version of a package will _ever_ have the same release info, it's not explicitly impossible. Highly improbable, yes, but possible as well. It's a bummer and unfortunately that is a very low level problem dictated by our build program for habitat packages which means its not something builder can account for.

So for now, that endpoint above will get updated to output the target info and once we have that we'll consider this issue closed for now! I hope that's helpful if also bit disappointing :(

**Comment by eeyun** [comment]
@gsloan-chef it turns out on deeper investigation this problem is a bit more complex than we were hoping. This is work that will get done at _some_ point but for more details I'd take a look over at #1111. When that's completed, this issue will also be resolved.
