### ISSUE TITLE
Attempting to connect to Docker Hub Integration fails

### ISSUE THREAD

**Issue by drrk** [habitat-sh/builder#1138]
### Scenario:
From the Integrations Tab on Bldr create the integration to Docker hub

### Steps to Reproduce:
Login to Bldr
Go to Integrations Tab
Remove existing DockerHub Integration if you have one
Click Docker Hub Button
Add credentials
Click Save Account

### Expected Result:
Integration is created

### Actual Result:
Error `Username and password combination is not valid` is returned.

The Credentials have been tested by logging into docker hub directly.
This was reported to me by jgh on Community Slack, and I reproduced.

**Comment by adamhjk** [comment]
this is also broken for AWS - you get an error reporting the URL of the registry is an invalid tag.

**Comment by jhelfman** [comment]
When this bug was put in, it was not broken for AWS. I successfully complete a lab associate with publishing and I did do this to ECR service in AWS.

**Comment by jhelfman** [comment]
> this is also broken for AWS - you get an error reporting the URL of the registry is an invalid tag.

When this bug was put in, it was not broken for AWS. I successfully completed a lab associate with publishing and I did do this to ECR service in AWS.

From log I just ran:
✓ Uploaded image '357855731650.dkr.ecr.us-west-2.amazonaws.com/learn-chef40/effortless/jgh:latest'
★ Docker image '357855731650.dkr.ecr.us-west-2.amazonaws.com/learn-chef40/effortless/jgh' published with tags: 0.2.0-20190807230803, 0.2.0, latest
» Cleaning up local Docker image '357855731650.dkr.ecr.us-west-2.amazonaws.com/learn-chef40/effortless/jgh' with all tags

**Comment by raskchanky** [comment]
Should be fixed by https://github.com/habitat-sh/builder/pull/1139
