### ISSUE TITLE
[Builder UI] Origin - Package tab revamp 

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/builder#1178]
## Problem
Currently, the page contains two tables: one table for packages that have connected plans; one table for packages that only have uploaded artifacts. Essentially they are all just packages inside the origin, but it unnecessarily highlights the ones with connected plans by grouping them into a separate table on the top.
The current solution looks like this (problem areas are highlighted with a red square):
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/5cf9f1c3-8ef8-4dda-a05e-e90389d1dc31)

Also with the introduction of multi-platform (target) packages, whether the package has plan connected or not is no longer the primary characteristics for a package. Because a package can have one plan file connected for each platform. The new model looks like this:
![image](https://user-images.githubusercontent.com/9401459/66525257-b9daaf00-eaa9-11e9-9ad8-792edf5eb982.png)

Therefore, we would like to redesign the packages tab to reflect that simplified model.
## Solution
The current solution looks like this (proposed changes are highlighted with green squares) : 
![image.png](https://images.zenhubusercontent.com/5a721a104b5806bc2bc51768/9e99b32f-cb4f-4a82-9fda-1f4218fb8ab4)

## Acceptance Criteria
- In Origin - Package tab, combining two tables into one package table. The table contains two columns: `package name` and `platform`.
- Show the available platforms for each package with icons. 
    - Available platforms for SaaS Builder: there is either a plan file connected for that platform or there is at least one artifact (.hart file) uploaded for that package.
    - Available platforms for On-prem Builder: there is at least one artifact (.hart file) uploaded for that package.
- Add the sidebar to show the default package visibility once a new package is created in this origin
- Add the instruction with links to docs describing how to upload packages manually to this origin.
Docs link: https://www.habitat.sh/docs/using-builder/#upload-and-promote-packages

## Implementation Notes
We need to change the package API to include the target(platform). @eeyun will investigate the impact of change to know where else it is used and then implement the API to support this UI change.

## Demo
For both SaaS and On-prem Builder:
- visit "my origins" page, select an origin from the table
- in the "packages" tab, see a table containing all the packages in the origin with their names appear in the `package name` column.
- for packages that have either a plan file connected for any platform or an artifact uploaded to, see the supported platform icons (Linux, Linux2, Windows, macOS) in the `platform` column
- for packages that have no plan files connected for any platform and no artifacts uploaded to, no platform icons are shown.

## UX Design
https://chef.invisionapp.com/share/E4U4DEYPZM2#/385988962_origin-Packages

**Comment by SEAjamieD** [comment]
@eeyun - has the API been updated to provide the target/platform mentioned in this comment above.

>We need to change the package API to include the target(platform). @eeyun will investigate the impact of change to know where else it is used and then implement the API to support this UI change.

I'm not seeing it listed so checking with you.  Thanks!

**Comment by SEAjamieD** [comment]
Currently Blocked by: Updating Package API to include target(platform)

**Comment by eeyun** [comment]
I'm not sure where this comment is coming from can you share the link to where this comment is? Right now the route "/depot/pkgs/{origin}" maps to the get_packages_for_origin function which i believe ultimately returns `Result<(Vec<PackageIdentWithChannelPlatform>, i64)>` which should have all of the data required. Unless we're needing a transform on that data or something before the UI can leverage it appropriately?

**Comment by SEAjamieD** [comment]
@eeyun - thanks for pointing out that endpoint!  I've got what I need now and the endpoint is returning exactly what was expected.  Working on getting this finished now.

**Comment by SEAjamieD** [comment]
@scottopherson and I spent a considerable amount of time yesterday looking into this ticket, and we came across some blocking issues for us.

Problems with endpoint for us
1. Packages separated by version and platform, so we essentially get multiple of each package in the array returned.  Ruby26 is a good example.  Can we merge by platforms/names.
1. The packages being returned by `/depot/pkgs/{origin}` are separated out by version and/or platform, so we essentially back duplicates under the same name.  "Ruby26" is a good example.  Instead of seeing something like `{name: ruby26, platform: [linux, windows]}` we get back {name: ruby26, platform: [linux]}, {name: ruby26, platform: [windows]}.

2. Range start and end on the second call to get packages via "fetchMorePackages()", which is for pagination is coming back with only 45 and then `totalCount` reflects the amount of data in the current packages array, not the true total count.

For example: on the first call to get Packages, an array is returned with range 0 to 49, and a total count of 599.  On the second call to get Packages, an array is returned with range 0 to 45, and a total count of 46.


For Liz / UX:
1. How are we combining the two lists of Projects and Packages?  
Right now we are calling two different endpoints that have two different sets of data inside.  We can merge the two in some fashion, but then pagination is out of whack.  This might not be much of a concern after some of the above is figured out.

**Comment by eeyun** [comment]
Ok, I've proven out a couple possible paths to get you all some data thats a little closer to what you're looking for, but, I wanted to get some of the discovery work I did documented here for the builder team (@chefsalim, @smacfarlane, @jeremymv2) to review before I go any further down this hole:

So here's what's up. As was mentioned in a different issue, we have 2 different APIs for origin packages. One of which (the one listed above) `/depot/pkgs/{origin}` returns all of the types of data you might want, but returns an entry for each individual release of a package. This endpoint is broken in a bunch of other ways that I haven't even investigated but of note it doesn't actually filter down packages based on origin. To this point in time that route is not used by the UI. 

The second available api for origin packages is the inversion of that route - `/depot/{origin}/pkgs`. Currently this endpoint follows a path that only returns top level packages for an origin but the data in that data set pretty much only consists of Origin and Package name. In further investigating that endpoint it appears we follow a different path of ORM code to get those appropriate responses, the data we return is paired down and we plug them into a much more limited data struct than the other API. What's more, the data on both of these tables is coming from the `origin_packages` table. That table is pretty damn big. Also, it doesn't include data from packages that have been created without a package being uploaded or a planfile connected. 

The single biggest issue with all of these paths is that in our current data architecture and our current REST APIs I don't see a mechanism in which we can get both the empty and uploaded packages with a single query. So I see multiple paths forward but none of them are really ideal, they all have some tradeoffs and I'll try to outline a couple here. 

1. We extend the more limited endpoint `/depot/{origin}/pkgs` to include a platform list, we use new data structures in the backend to model this and we end up with a new responses from that endpoint that looks something like:
```
{ 0: { origin : "habitat", name : "airlock", platforms :  [Linux, Windows, Linux2],}.
1: {origin: "habitat", name: "builder-api", platforms: [Linux], etc}
```
Of course the thing to remember is we still won't be able to return data on this endpoint that tells us if the platforms are empty from a single query and putting the data together from the two available tables could be painful.

2. We fix the previously mentioned api `/depot/pkgs/{origin}` so that it returns appropriate datasets and so that it has appropriate pagination. We can alter the query it uses to get cleaner output like the above,  serialize that data into a similar new struct and end up with virtually identical output to the previous solution. Similarly to above, we run into the same limitation here. We have to make 2 separate queries in this code-path that allow us to get the data and populated the data structure here if we want to be able to render both empty packages and packages with uploads. It could be somewhat painful to collate.

3. We can add a new endpoint. If we go this path  we have a few options. Mostly, this option looks a lot like the previous two options in implementation unless we wanted to make the endpoint a graphql API rather than a REST one. In that case, we might be able to introduce a very minimal graphql schema that would allow the frontend to request the specific bits of data they need from both tables without making multiple round trips and without us having to do so inline on the back end. This would be a bit more work relatively than the other two but could also have more benefits going forward.

If you've got an idea for another option, please call it out here. This problem is actually a bit more involved and complex than I originally thought it would be so there could be quite a few other ways to solve it that I'm not seeing.

**Comment by jeremymv2** [comment]
@eeyun @chefsalim I think as we're building out this new package paradigm we should take the time now to invest in making our stack more flexible to handle these types fundamental changes our underlying current assumptions in the future. 

With that in mind, I'm leaning towards option 3 with GraphQL. Although it introduces a new learning curve and the associated risks that brings, I think it has the most potential payoff for the time spent.

**Comment by eeyun** [comment]
OK! We have a consensus which is - we're going to avoid displaying the package target information on that view for now. Instead, we're going to alter that route to return the top-level package information from the newly formed `origin_package_settings` table which will give you a nice quick response of all the top level packages in an origin whether or not a binary exists, and we should be able to provide pagination over that dataset as well. @SEAjamieD and @scottopherson let me know if you have any questions on this before I dive in!

**Comment by SEAjamieD** [comment]
@eeyun - That sounds solid to me!
