### ISSUE TITLE
enhance API to return origin owner account name

### ISSUE THREAD

**Issue by jeremymv2** [habitat-sh/builder#1272]
### Describe the Enhancement:
Currently we return `owner_id` (i64) when querying the API for an origin or an origin's member list.
It would be nice to be able to map the id into the human friendly account name.

### Describe the Need:

This will allow users of hab CLI or the Bldr UI to easily identify an origin's owner.

**Comment by eeyun** [comment]
For some hopefully helpful context for whoever works this issue: 

Currently the origins table includes the following entries: 
`name, owner_id, created_at, updated_at` 

while the origin_members table includes: 
`origin, account_id, created_at, updated_at`. 

The `list_origin_members` function searches the origin_members table and does an inner join on the accounts table to get the users name as well as ID on the returned dataset but since the `owner_id` is only stored in the origins table we probably need to think about what makes the most sense with the current data architecture. I think its probably not a super expensive call to hit `origins` but obviously every inner_join should be carefully considered due to potential slow response times.

Somewhat related: any change to the returned data structure here would probably be considered breaking (which should absolutely not scare us away, I just wanted to make sure we call it out).

**Comment by jeremymv2** [comment]
@chefsalim, @eeyun, what do you think about the idea of solving this problem by introducing a new endpoint: `/user/<id>` that returns non sensitive data about the user? If we had that, we could just make a 2nd API call passing the origin owner id to get a user friendly display name.  We wouldn't have to worry about any performance degradation of the `list_origin_members` function nor any breaking changes to its data structure.

**Comment by chefsalim** [comment]
I'm not sure we need to worry about this too much - these are tiny tables / simple join, and adding a JSON member should in theory not be breaking backward compat. So original plan seems ok to me.
