### ISSUE TITLE
Hab origin delete - doesn't work after promoting and removing package

### ISSUE THREAD

**Issue by y-me-y** [habitat-sh/builder#1277]
### `hab` CLI version
0.88.0 

### Platform Details
10.15.2

### Scenario:
Delete an 'empty' origin

### Steps to Reproduce:
1. Create origin using cli or webui
1. build and upload package to origin you created
1. tag package with a channel like - `deletetest`
1. delete package from origin
1. using the cli delete the origin

### Expected Result:
delete origin successfully 

### Actual Result:

Because a record was created in the `audit_package` table we are unable to delete the origin. 

```bash
☒ Deleting origin testorigin.
✗✗✗
✗✗✗ Unable to delete origin testorigin
✗✗✗
✗✗✗
✗✗✗ Origins may only be deleted if they have no packages, linked projects
✗✗✗
✗✗✗
✗✗✗ or other dependencies. Please check your origin and try again.
✗✗✗
✗✗✗
✗✗✗ [409 Conflict]
✗✗✗
```

if I go into the db and delete the record `delete from audit_package where origin = 'testorigin';`I am able to delete the origin

```
☒ Deleting origin testorigin.
✓ Deleted origin testorigin.
```

**Comment by jeremymv2** [comment]
Origin deletion, as currently implemented, will not work via `hab origin delete`
if the origin was previously "used". As the cli help message indicates, it only
deletes an unused/empty origin.

The work effort associated with this issue will be to enable the command to work
without increasing the risk of accidental or unintentional origin deletion.

Initial questions and concerns:
 - Should we require multiple approvals? We don't have RBAC and only the concept of a single origin owner. Without RBAC we probably can't do this. 
 - Currently the hab cli origin deletion command has no prompt for confirmation or warnings
 about the potential impact of an origin deletion. 

Initially, I thought to implement the backend API call via a single delete in the origins
table and with all linked tables using `ON DELETE CASCADE`. However, this approach
almost makes the deletion too easy and increases the risk of accidental and catastrophic
origin deletion. Especially since, to date, the hab CLI has zero warnings / confirmations around the command.

My new approach will be to shift away from ON DELETE CASCADE and placing the brunt of the work
onto the user. While I would normally not espouse the idea of making tasks more laborious for
the end user, deleting an origin shouldn't be done in a hurry and we want to invoke
a sense of definite intentionality from the user.

With that in mind, the `hab origin delete` command will continue to NOT work if there is any existing data in the origin.  The user must first clean up the origin data via commands that already exist in the CLI or via the Bldr UI. I will update the hab cli, so that on error,  it will output all the commands necessary for the user to check and/or delete the origin data.

The full list of pre-requisite tasks they will be required to do is:
 - delete all packages (in order to do so they cannot be in the stable channel nor have any rdeps)
 - remove all members
 - delete all secrets
 - delete all integrations
 - delete all projects
 - delete all channels other than unstable|stable

--
Required database changes:

// We want to keep package audit records, even after deletion of the origin.
// Removing the fkey allows the origin to be deleted and these records to remain.

Tables to remove fkey from:
 - audit_package
 - audit_package_group

// We probably also want to store origin deletion operations
Create new `audit_origin` table to hold origin modification data.

--
Rust Implementation:

 - Update the hab cli to include a confirmation prompt, warnings, and to output the commands necessary for origin cleanup.

 - In builder-api/src/server/resources/origins.rs
   - sanity check via SQL calls that tables below do NOT have any origin references remaining.
      origin_members
      origin_secrets
      origin_integrations
      origin_projects
      origin_channels
      origin_packages

 - In builder-db/src/models/origin.rs
   - run transaction to delete the origin from all tables
      origin_public_keys
      origin_secret_keys
      origin_channels
      origin_members
      origin_package_settings
      origin_integrations
      origin_invitations
      origin_packages
      origin_private_encryption_keys
      origin_projects
      origin_public_encryption_keys
      origin_secrets
   - some of the above is redundant but best to be explicit here..
 - run a transaction to delete from origins table and to add into audit_origin table

--
Testing:
  - cover origin deletion operation with end-to-end tests
