### ISSUE TITLE
[on-prem depot] Personal access tokens API

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/builder#129]
The backend and the UI both need to be using access tokens that we control, not GitHub access tokens, for authenticating API requests.  There is a card already to track the UI work [here](https://github.com/habitat-sh/builder/issues/101).

**Comment by cnunciato** [comment]
In order to support the current designs, we need APIs that let us:

* know whether a token already exists
* generate a new token
* know something useful about an existing token (e.g., when it was created)
* delete an existing token

Thinking ahead, we might also want to support users having multiple personal access tokens, though we don't have a specific requirement for this just yet.

So I'm thinking we might start with these:

```
# Where one or more tokens exist:
GET /profile/access-tokens
-> 200
[
  {
    id: some-id,
    created_at: "2018-01-26T18:24:18.123464+00:00"
  }
]

# Where no tokens exist:
GET /profile/access-tokens
-> 200
[]

# To generate a new token:
POST /profile/access-tokens
-> 201
{
  id: some-id,
  token: 'my-newly-generated-token-value',
  created_at: "2018-01-26T18:24:18.123464+00:00"
}

# To delete a token:
DELETE /profile/access-tokens/:id
-> 200
``` 

This would give us all of the bulleted requirements above, support multiples in the future if we need to, and support additional token metadata (e.g., name, etc.) if that becomes useful at some point. 

Thoughts? cc @chefsalim @raskchanky

**Comment by chefsalim** [comment]
Looks great @cnunciato !

**Comment by raskchanky** [comment]
Sounds great @cnunciato :shipit:

**Comment by chefsalim** [comment]
Pushed to live - closing
