### ISSUE TITLE
Improve Builder API bandwidth usage

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#1293]
Frequently the hab client needs to call the Builder API to perform checks to determine: 1) whether a given package exists, and 2) retrieve the latest ident of that package

This is done by calling APIs such as : `/depot/channels/{origin}/{channel}/pkgs/{pkg}/{version}/latest`

These API calls return the full package metadata as a JSON body, which can be larger than necessary.

This card is to add variants of the APIs (perhaps with a query param for brief output) that allows for the checks to proceed without verbose data being returned. 

There will need to be corresponding change made to the Hab client to use the new API format.

**Comment by jeremymv2** [comment]
The http `HEAD` call would be a fine method for checking existence.

**Comment by chefsalim** [comment]
Yep, that would work - it would mean sprinkling a bunch more handlers that would be the only downside vs handling via query param

**Comment by eeyun** [comment]
I have this implemented and working with new `HEAD` route handlers for the example above. Instead of receiving a payload response we get a nice light response like so:

```
┌─╼[~] 
└╼  curl --head http://localhost/v1/depot/channels/core/unstable/pkgs/bash/4.4.19/latest    
HTTP/1.1 200 OK
Server: nginx/1.17.8
Date: Wed, 04 Mar 2020 10:54:37 GMT
Content-Type: application/json
Content-Length: 8
Connection: keep-alive
x-pkg-ident: {"name":"bash","origin":"core","release":"20190115012619","version":"4.4.19"}
cache-control: private, no-cache, no-store
Cache-Control: private, no-cache, no-store
```
Right now I'm considering adding `HEAD` handlers to the rest of any routes that have a `/latest` call however, I'd like to validate are there any other endpoints we'd like to provide with this functionality?

**Comment by jeremymv2** [comment]
@eeyun, I have a few more thoughts on the `HEAD` method that I want to get your input on.

1. To me, the `HEAD` method makes most sense when used in the 1st scenario @chefsalim mentioned at the top of this issue; ie. to minimize the bandwidth required when wishing to simply check for the _existence_ of a package. This appears to be the exact scenario for our [check_package](https://github.com/habitat-sh/habitat/blob/ab0d73db1331e277e788930ef2cd59ad1746bac0/components/builder-api-client/src/builder.rs#L1023-L1044) function. It's currently used in [pkg upload](https://github.com/habitat-sh/habitat/blob/537171161d54a27e1dbc37210bc22d9359c75cca/components/hab/src/command/pkg/upload.rs#L69) and, if you think about it, is an extremely wasteful use of bandwidth and time. Imagine how much quicker an upload would be if we sprinkled `HEAD` on that, especially in bulkuploads 🚀 
2. According to the [RFC](https://tools.ietf.org/html/rfc7231#section-4.3.2)
> The server SHOULD send the same
   header fields in response to a HEAD request as it would have sent if
   the request had been a GET
🤔 
3. Implementing `HEAD` on the `../latest` endpoint has the lowest value proposition to me.  It feels like we perhaps are not in sync with the recommendation in 2) above. Also, the bandwidth saved there seems to be very minimal. For example, `curl -L -XGET -H "Authorization: Bearer $HAB_AUTH_TOKEN" http://bldr.habitat.sh/v1/depot/channels/core/unstable/pkgs/hab-sup/1.5.50/latest` amounts to just 124KB.

**Comment by eeyun** [comment]
I'm good with adding `HEAD` for cases where we don't want to return data, it felt bad to me to add custom headers for these specific routes. Checking whether a package exists is a good use case. Maybe the most important usecase of the API though I would be willing to bet the net amount of bandwidth saved is going to remain low for each call since most of the objects returned by many of these endpoints are more or less synonymous.
