### ISSUE TITLE
Cannot open any public package without login at bldr.habitat.sh

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/builder#1389]
1. Go to builder
2. Find any public package
3. Open it

Expected Result: Package view is opened
Actual Result: Sign In page is forced

**Comment by jsirex** [comment]
UPD: 
4. Sign in into builder
5. Open public package you don't own

Expected Result: Package view is opened
Actual Result: Sign In page is forced

**Comment by jeremymv2** [comment]
Just a note on the why: as of 2 releases ago, the frontend UI now queries `/settings/{origin}/{pkg_name}` and gets a 401 because there is no existing session. The backend API `/settings` endpoint expects an existing session token, and for it to be a member of the target origin:

https://github.com/habitat-sh/builder/blob/75682134f5a547666f6341c53d1fe208ad219242/components/builder-api/src/server/resources/settings.rs#L59-L61

**Comment by jeremymv2** [comment]
**Context**
The frontend UI is making a request to `https://bldr.habitat.sh/v1/settings/ORIGIN/PKG_NAME` in order to determine the package's `visibility` settings. The Package Visibility information is then displayed as either public or private.

The trouble arises here because the `/settings` API endpoint requires authentication information in the request as the visibility information can be considered sensitive metadata. If a user is unauthenticated, the UI receives a 401 unauthorized response from the backend `/settings` endpoint and forces the login window; even if the package was public.

**Possible Fix**
The UI understands if the user is current authenticated or not. In the event that the user is not, the UI could silently eat the 401 error and possibly display some helpful information that the package visibility setting for the package is missing until the user first authenticates.
