### ISSUE TITLE
Only public packages show Latest and Versions

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/builder#141]
It appears that when a package is marked as Private, nothing appears on the Latest or Versions tabs (when I'm signed in and a member of the origin, of course). The `/latest` API 404s, and the `/versions` API returns no results. I would expect to see information in both of these tabs when signed in an origin member.

**Comment by onlyhavecans** [comment]
I have experienced this when trying to set up my first repo.
It is a very broken experience as a new user.

**Comment by raskchanky** [comment]
@onlyhavecans Is this still a problem for you?  I've been trying to reproduce this problem locally and haven't had any success.  @cnunciato also attempted reproducing it on the live Builder site and couldn't.  We were having some rate limiting issues with GitHub a few weeks ago that has since been resolved, but I'm wondering if that caused the API to appear to not work.  Any chance you can give this another try and report back?
