### ISSUE TITLE
Use computed build manifest to build packages

### ISSUE THREAD

**Issue by markan** [habitat-sh/builder#1412]
@markan commented on [Fri May 01 2020](https://github.com/habitat-sh/habitat/issues/7664)

We would like to actually test that our generated manifests work. The best way to do this it actually build packages. 

We already have some scripts which are very near to what we what. Let's take the build manifest and execute the build in the order it specifies, and see what we get.

This will most likely require 
1) adapting the scripts slightly to work with the build manifest
2) standing up a scratch builder instance and a worker node to do builds on
3) Running them for a while to see what we get for our packages (this will be a multi-day process for gcc)
4) Running a verification pass on the packages to ensure that they are as we expect

This serves multiple purposes. The obvious one is that it lets us cheaply (developer time at least) test that we have a good order. But also, this should be a usable way to generate builds if we need to update things before builder has full cyclic build support.

**Comment by smacfarlane** [comment]
This work has been completed successfully. The only issue identified is that we need to shrink the build arc between glibc and gcc such that only runtime dependencies of gcc are built between the two.

Below is the number of expected packages and the actual number of built packages.  The delta is from packages that are in the core origin, but not part of the core-plans repository (deprecated, moved, etc.) or packages that failed to build due to issues unrelated to ordering (ex: upstream source has moved). All packages that failed to build are leaf packages (no other packages have dependencies on them), so ordering doesn't matter and this can still be considered a success.

```
721  workspace/cyclic-build-order.txt
694  workspace/built_pkgs.db
```
