### ISSUE TITLE
Better differentiate error sources in Builder Worker jobs

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#157]
@christophermaier commented on [Wed Feb 07 2018](https://github.com/habitat-sh/habitat/issues/4571)

When a build fails in Builder, it can be unclear exactly where the failure is coming from; in many cases, it can just be effectively an opaque "Error: exit code 1".

In particular, being able to differentiate between failures that we control, vs. failures arising from a `plan.sh` file with errors, will allow us to more quickly fix issues, and also surface potential service-degrading issues via monitoring and alerting.

**Comment by chefsalim** [comment]
Error handling is refactored in this PR to better differentiate high level causes and have friendler error code (instead of a number) - https://github.com/habitat-sh/builder/pull/155

However differentiating a failure due to a malformed plan file vs. some other cause is currently difficult - ultimately, the worker only knows about an exit code that is returned by studio.
