### ISSUE TITLE
Builder rdeps API works incorrectly

### ISSUE THREAD

**Issue by sajjaphani** [habitat-sh/builder#1647]
The rdeps API is not returning any results for the following packages:
    core/linux-headers-musl
    core/python-minimal

**Comment by sajjaphani** [comment]
Builder 'rdeps' API seems working properly. Below are the observations on the listed packages:

core/python-minimal -> No package (core-plans, chef-base-plans) depends on this package.
core/linux-headers-musl -> busybox-static (chef-base-plans) lists this package as a dev dependency.

Currently, build dependencies are not enabled while finding reverse dependencies.

**Comment by timin** [comment]
Package "python-minimal" is build time dependency for "glib"
https://github.com/chef-base-plans/glibc/blob/4c34bec06b90a63e0999948e916e02a99b6d82ca/plan.sh#L30

though Builder API (curl -si https://api.habitat.sh/v1/rdeps/core/python-minimal) show no dependents.

Similarly for package "linux-headers-musl" is dependency for "wget-static", "jo" and "busy-static" but Builder API (curl -si https://api.habitat.sh/v1/rdeps/core/linux-headers-musl) results in no dependents.

It is unexpected behaviour by API since we can verify dependency tree by searching planfiles of Core Packages. This is based on dependency relationship among Core Packages, user packages (habitat, infra, workstation etc) dependency relationship can not be verified. I guess dependency data is not updated with every HART file upload to reflect change in dependency tree with changes in planfile.

**Comment by timin** [comment]
Furthermore, I have observed that Builder API returns success response code (HTTP 200) in cases where it should have error code(return code) while testing few scenarios

1. Package name is not present - package named "abc" is not present yet Builder API returns 200 response code
e.g. curl -si https://api.habitat.sh/v1/rdeps/core/abc

2. Orgin name is not present - origin named "abc" is not present yet same result as above
e.g. curl -si https://api.habitat.sh/v1/rdeps/abc/php

3. combination of #1 and #2

Response code of API gives impression that is package or origin is present and does not have any dependents which is false. And as per API docs when package is not found response code should be 404. I guess either API behaviour or API docs needs to updated.
