### ISSUE TITLE
Build Highly Available Builder ( On Prem Setup )

### ISSUE THREAD

**Issue by rahulgoel1** [habitat-sh/builder#1676]

**Comment by sajjaphani** [comment]
https://github.com/habitat-sh/on-prem-builder/issues/253

**Comment by mwrock** [comment]
closing this. The intent of this was to manually provision a scaled out builder environment in order to get the feel of how the automation would look. I have done some building and provisioned a working load balancer. However at this point I feel like we have conducted enough discovery to start moving forward with the automation and will create issues to cover that.
