### ISSUE TITLE
Research and Analyze Builder Load WorkBench for Performance Testing of HA builder

### ISSUE THREAD

**Issue by rahulgoel1** [habitat-sh/builder#1677]

**Comment by mwrock** [comment]
https://github.com/habitat-sh/builder-bench was developed by a previous team member. That tool can be pointed to a builder URL and will query all packages in the core origin and then loop through each of those packages and download them.

It is currently running on the three bastion nodes in the acceptance environment and pointed to acceptance builder. From what I have been able to determine looking through internal slack archives, we use this to tell if a specific builder release causes a performance degradation. We fire a datadog event on each release so it should be possible to review datadog logs in acceptance around a release to see if there was a drop in requests/sec.

This tool also provides some convenience reporting. For example you can tell it to run for 5 minutes and on completion it will tell you tot requests per second, total requests and some other metrics.

I installed it on a few different nodes and bumped the thread count (you can specify number of threads to send requests on) to simulate enough traffic to see when we could expect failures to start. I found the tool to be "not great" for this. First the output was difficult to read, second I was seeing lots of 422 (UNPROCESSABLE_ENTITY) responses from builder which I am not sure were from load or the way the tool was forming the request.

In order to truly simulate a high traffic customer environment (1000s of supervisor requests per second) we would need more infra structure and the tool would need more work. My recommendation is that we move forward with making builder easier to setup for HA and if we really feel like we need to have more load testing metrics, we spin that up as a separate effort later. Otherwise we could get bogged down in load testing minutiae when we know that there are customer environments that need a scaled out builder and that work is pretty clear.
