### ISSUE TITLE
[builder-web] Temporarily stop validation of plan path when connecting a plan

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#236]
Until we get the github rate limit issue under control, we should have a workaround of not using the /ext/installations API endpoint.  We can do this by not validating the plan path.  It would be great to have this behind a config/feature flag.

**Comment by cnunciato** [comment]
After some discussion with @chefsalim, I'm going to close this. It turns out that removing the validation won't have much of an impact on the user experience after all, because when a plan is submitted, Builder makes an immediate call to GitHub to retrieve and parse the plan file, and this call would itself fail under the rate-limited scenario we're attempting to handle by removing the validation. 

The WIP branch is here, though, in case we decide to do this after all:

https://github.com/habitat-sh/builder/tree/cdn/non-validated-plan-select
