### ISSUE TITLE
[builder-depot] Builder incorrectly uses user-agent to determine target platform for package uploads

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/builder#258]
I ran into the following error today, attempting to upload a Linux package from MacOS 

```
» Uploading results/smacfarlane-np-mongodb-3.2.9-20180306171108-x86_64-linux.hart
∵ Missing artifact for core-cacerts-2017.01.18-20170513215104-x86_64-darwin.hart was not found in results
^C
~/s/c/np-mongo ❯❯❯ hab --version                                                                                                                                                                                                     hab 0.54.0/20180221020527
```

Ref: https://github.com/habitat-sh/habitat/issues/4097 (fixed: https://github.com/habitat-sh/habitat/pull/4194)

Digging into it a bit, I suspect the error is coming from Builder and not Hab, specifically the `target_from_headers` function, used in the following two lines.  Based on debug logs below, the mac client sets `user_agent_header: UserAgent("hab/0.54.0/20180221020527 (x86_64-darwin; 17.3.0)")` which Builder uses, rather than the target platform of the package. 

https://github.com/habitat-sh/builder/blob/master/components/builder-depot/src/server.rs#L1713
https://github.com/habitat-sh/builder/blob/master/components/builder-depot/src/server.rs#L1750

Debug Logs: 
```
» Uploading results/smacfarlane-np-mongodb-3.2.9-20180306171108-x86_64-linux.hart
DEBUG 2018-03-06T17:23:48Z: habitat_http_client::api_client: GET https://bldr.habitat.sh/v1/depot/pkgs/smacfarlane/np-mongodb/3.2.9/20180306171108 with ApiClient { endpoint: "https://bldr.habitat.sh/v1", inner: Client { redirect_policy: FollowAll, read_timeout: Some(Duration { secs: 60, nanos: 0 }), write_timeout: Some(Duration { secs: 60, nanos: 0 }), proxy: None }, proxy: None, target_scheme: "https", user_agent_header: UserAgent("hab/0.54.0/20180221020527 (x86_64-darwin; 17.3.0)") }
DEBUG 2018-03-06T17:23:48Z: hyper::http::h1: request line: Get "/v1/depot/pkgs/smacfarlane/np-mongodb/3.2.9/20180306171108" Http11
DEBUG 2018-03-06T17:23:48Z: hyper::http::h1: headers=Headers { Host: bldr.habitat.sh
, User-Agent: hab/0.54.0/20180221020527 (x86_64-darwin; 17.3.0)
, Authorization: Bearer c1ec4371f47608fe725feb38d8eaba625881162b
, }
DEBUG 2018-03-06T17:23:49Z: hyper::client::response: version=Http11, status=NotFound
DEBUG 2018-03-06T17:23:49Z: hyper::client::response: headers=Headers { Access-Control-Allow-Headers: authorization, range
, Access-Control-Allow-Methods: PUT, DELETE, PATCH
, Access-Control-Allow-Origin: *
, Access-Control-Expose-Headers: content-disposition
, Content-Type: application/json; charset=utf-8
, Server: nginx/1.12.2
, Content-Length: 42
, Accept-Ranges: bytes
, Date: Tue, 06 Mar 2018 17:23:49 GMT
, Via: 1.1 varnish
, Age: 0
, Connection: keep-alive
, X-Served-By: cache-sea1036-SEA
, X-Cache: MISS
, X-Cache-Hits: 0
, Vary: Accept-Encoding
, Strict-Transport-Security: max-age= 7776000; includeSubDomains
, X-Frame-Options: SAMEORIGIN
, }
DEBUG 2018-03-06T17:23:49Z: habitat_http_client::api_client: GET https://bldr.habitat.sh/v1/depot/pkgs/core/cacerts/2017.01.18/20170513215104 with ApiClient { endpoint: "https://bldr.habitat.sh/v1", inner: Client { redirect_policy: FollowAll, read_timeout: Some(Duration { secs: 60, nanos: 0 }), write_timeout: Some(Duration { secs: 60, nanos: 0 }), proxy: None }, proxy: None, target_scheme: "https", user_agent_header: UserAgent("hab/0.54.0/20180221020527 (x86_64-darwin; 17.3.0)") }
DEBUG 2018-03-06T17:23:49Z: hyper::http::h1: request line: Get "/v1/depot/pkgs/core/cacerts/2017.01.18/20170513215104" Http11
DEBUG 2018-03-06T17:23:49Z: hyper::http::h1: headers=Headers { Host: bldr.habitat.sh
, User-Agent: hab/0.54.0/20180221020527 (x86_64-darwin; 17.3.0)
, Authorization: Bearer c1ec4371f47608fe725feb38d8eaba625881162b
, }
DEBUG 2018-03-06T17:23:51Z: hyper::client::response: version=Http11, status=NotFound
DEBUG 2018-03-06T17:23:51Z: hyper::client::response: headers=Headers { Access-Control-Allow-Headers: authorization, range
, Access-Control-Allow-Methods: PUT, DELETE, PATCH
, Access-Control-Allow-Origin: *
, Access-Control-Expose-Headers: content-disposition
, Server: nginx/1.12.2
, Content-Length: 0
, Accept-Ranges: bytes
, Date: Tue, 06 Mar 2018 17:23:51 GMT
, Via: 1.1 varnish
, Age: 0
, Connection: keep-alive
, X-Served-By: cache-sea1036-SEA
, X-Cache: MISS
, X-Cache-Hits: 0
, Strict-Transport-Security: max-age= 7776000; includeSubDomains
, X-Frame-Options: SAMEORIGIN
, }
∵ Missing artifact for core-cacerts-2017.01.18-20170513215104-x86_64-darwin.hart was not found in results
∵ Missing artifact for core-cacerts-2017.01.18-20170513215104-x86_64-darwin.hart was not found in results
∵ Missing artifact for core-cacerts-2017.01.18-20170513215104-x86_64-darwin.hart was not found in results
∵ Missing artifact for core-cacerts-2017.01.18-20170513215104-x86_64-darwin.hart was not found in results
∵ Missing artifact for core-cacerts-2017.01.18-20170513215104-x86_64-darwin.hart was not found in results
✗✗✗
✗✗✗ Upload failed: We tried 5 times but could not upload core/cacerts/2017.01.18/20170513215104. Giving up.
✗✗✗
```

**Comment by raskchanky** [comment]
This is slightly more subtle than it first appears.  From what I can tell, Builder isn't actually involved at all in this one.

To reproduce this problem, I downloaded the latest version of `core/redis` and its two dependencies to my local working directory.  I exported `HAB_AUTH_TOKEN` and `HAB_BLDR_URL` env vars to point to my local depot and then ran:

`hab pkg upload ./core-redis-3.2.4-20170514150022-x86_64-linux.hart`

And everything worked just as it should.  Then I tried it for a hart file that I did not have the dependencies for.  My next test was:

`hab pkg upload ./core-perl-5.22.1-20170513213942-x86_64-linux.hart`

I _did_ have this hart in my local working directory, but I didn't have any of its deps.  This succeeded in reproducing the same error listed above.  Tracing the problem through, I believe the actual error message is emitted [here](https://github.com/habitat-sh/habitat/blob/master/components/hab/src/command/pkg/upload.rs#L273-L280).  The formatting of this error message lines up exactly with what was reported, and it corresponds to not being able to find the file on disk.

`ident.archive_name().unwrap()` is the actual code that spits out the file it couldn't find.  This code is [here](https://github.com/habitat-sh/core/blob/master/components/core/src/package/ident.rs#L93-L95) and you'll notice that it passes `&PackageTarget::default()` for the target to display.  That code is [here](https://github.com/habitat-sh/core/blob/master/components/core/src/package/target.rs#L89-L94) and you'll notice that it is emitting values for the architecture that this command is being run on, in this case macOS.

I was able to verify, however, that the `candidate_path` that the upload code is looking for [here](https://github.com/habitat-sh/habitat/blob/master/components/hab/src/command/pkg/upload.rs#L258-L261) does contain the correct target, which explains why everything works perfectly when all of the required dependency files are present.

In this case, I think the fix is to just pass along the correct target that the upload code already has, rather than relying on the ident to deduce that for us.  I should have a PR correcting this soon.
