### ISSUE TITLE
Builder: better error messages when having github authentication errors

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/builder#288]
@dongsupark commented on [Wed Nov 29 2017](https://github.com/habitat-sh/habitat/issues/4153)

When testing Habitat Builder I have seen strange cases where it's impossible for any plan to be connected. It means, on the web UI, connecting to plan hangs forever. In that case, there's no error at all, neither on the web UI nor in the bldr log.

The only warning that looks suspecious in the bldr log is like that:

```
sessionsrv.1 | WARN:habitat_builder_sessionsrv::server::handlers: Failed to obtain installation token, GitHub App Authentication error, message=Not Found, documentation_url=https://developer.github.com/v3/apps/#create-a-new-installation-token
```

However, the warning above is not actually meaningful, because it shows up no matter whether github authentication error happens or not. Rather the warning simply makes debugging harder.

In my case, the real reason was actually misconfiguration of client ID as well as client secret. If any error would have indicated an authentication error of client ID or client secret, it could have been much easier to track the issue.

It would be really great, if Habitat Builder could print out meaningful messages in case of github authentication errors.

/cc @schu @indradhanush @robertgzr

**Comment by chefsalim** [comment]
I'm not sure what we can do about this. If the client id/secret are incorrectly configured in the builder config, the error message is shown by the OAuth provider site upon redirect, and that is the behavior I observe attempting to repro this.  That said, since the issue was opened we have re-factored the OAuth provider, as well as added new error messages for auth failures on the back end when the occur.  

If you don't see the expected errors, please re-open this with exact repro instructions and we can look at it again.
