### ISSUE TITLE
Travis fast_pass seems to be broken

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/builder#323]
We have a script [here](https://github.com/habitat-sh/builder/blob/master/support/ci/fast_pass.sh) that's used to determine what (if any) tests need to be run on travis.  Once upon a time, it worked great, but it seems to be broken now.

A change to the CODEOWNERS file required a full test suite to run, and a change to the studio code required all the Rust tests to run (and the studio doesn't have any Rust code).

**Comment by baumanj** [comment]
Are you referring to [this travis run](https://travis-ci.org/habitat-sh/habitat/builds/355459461)? It seems like there is an issue with the way `AFFECTED_DIRS` is being handled. For the first matrix entry, [`AFFECTED_DIRS`](https://github.com/habitat-sh/habitat/blob/master/.travis.yml#L31) should be set to
```bash
"Cargo\.lock|$_RUST_HAB_BIN_COMPONENTS|$_RUST_HAB_LIB_COMPONENTS"
```
And [in the log](https://api.travis-ci.org/v3/job/355459462/log.txt), we see:
```
$ export AFFECTED_DIRS="Cargo\.lock|$_RUST_HAB_BIN_COMPONENTS|$_RUST_HAB_LIB_COMPONENTS"
```
But the output of the script only has
```
In the affected directories:

    Cargo\.lock
```
The  [second matrix entry](https://github.com/habitat-sh/habitat/blob/master/.travis.yml#L72) should have
```bash
AFFECTED_DIRS="Cargo\.lock|$_RUST_HAB_LIB_COMPONENTS
```
But [in the log](https://api.travis-ci.org/v3/job/355459463/log.txt), we see:
```
AFFECTED_DIRS is not set. Not exiting and running everything.
```
and no `export` at all.

I'm guessing this is due to the fact that [`_RUST_HAB_BIN_COMPONENTS` and `_RUST_HAB_LIB_COMPONENTS` definitions](https://github.com/habitat-sh/habitat/blob/8fa37fc0cfee7953bf3cd2df0081b833124498e3/.travis.yml#L15-L17) are missing closing quotes.

Fortunately, I was just working on [an unrelated change](https://github.com/habitat-sh/habitat/pull/4789) where I also fixed that issues, so hopefully it should be resolved when I merge that.

**Comment by raskchanky** [comment]
Right, but this issue is on the builder repo and that's on the habitat repo.  I guess we need to port your fixes over here?

**Comment by baumanj** [comment]
Did you have an instance of this issue on the builder repo? I looked, but didn't see one. I did see it doing the wrong thing on this [habitat travis run](https://travis-ci.org/habitat-sh/habitat/builds/355459461).

I don't see anything similarly wrong with the [.travis.yml](https://github.com/habitat-sh/builder/blob/master/.travis.yml) in the builder repo. And I've already made my changes to the [builder repo's fast_pass.sh](https://github.com/habitat-sh/builder/pull/208).

Can you still reproduce this issue?

**Comment by raskchanky** [comment]
For posterity, this is the travis run I was referring to:  https://travis-ci.org/habitat-sh/builder/builds/356599999

I made a change to the `CODEOWNERS` file and it was roughly 12 minutes before I received any feedback from Travis about the state of my PR.  I was under the impression that our `fast_pass.sh` script was capable of aborting Travis runs faster than that.  So it appears that our script is indeed running as intended and Travis is just slow 😂
