### ISSUE TITLE
Spike to investigate integration of RabbitMQ to Builder

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/builder#532]
Investigate / prototype - new libraries needed, setting up Rabbit with a persistent queue, allowing job server and worker to be able to send and receive from Rabbit queues.

**Comment by eeyun** [comment]
Ok so time to track out what we've found -

Good
====
RabbitMQ is definitely the tech we want to use for our job queuing. It fits our needs quite well and publishing messages to the queue with binary data as the payload e.g. a protobuf message is relatively trivial which means changing the `worker_manager` shouldn't be _too_ difficult depending on implementation. All around, i think RMQ is a solid choice for the queuing mechanism and I doubt we'd be disappointed given enough time to get comfortable with all it can do. Due to the system flexibility of routing, ease of maintenance and the scalability potential I'd be pretty surprised to come across another piece of OSS that does as much for so little investment.


Slightly less good
====
Now, the not so nice parts. As with many things in rust the _number_ of available AMQP libraries is limited. The lib I spent the most time investigating is [lapin-futures](https://github.com/sozu-proxy/lapin). This library supports end-to-end async behavior for both the producer and consumer functionality. The library ergonomics are at this point quite solid, the project is actively maintained, and the library supports almost anything we could need to do. Almost. 

As it stands right now I have been unsuccessful in getting the library to publish to a `topic` type exchange. For further detail on the problem I have opened an issue in the library [here](https://github.com/sozu-proxy/lapin/issues/134). What this means for our project's architecture is that we would have to use a `direct` exchange which would obligate direct routing from routing keys. What this all means is queue routing being less dynamic than it could be otherwise. It would also mean whatever sets up the binds between the queue and the exchange would need to have  list of routing keys it is aware of.  This doesnt inherentlyy break the design but it is worth being aware of. Should we be able to resolve this one remaining issue I think lapin could be a very solid library to use.

**Comment by eeyun** [comment]
Updates
=====
After further discussion we've decided to continue to use (for now) the ZMQ based job queuing mechanism in conjunction with making the worker_manager a bit smarter WRT what it can do to process those queued items. 

We are imagining a new state, at least initially, in which the worker_manager is capable of some of the behaviors that the @elliott-davis agent is capable of performing. In this way we can still abstract the task completion away from the jobsrv, the task-runner's can remain stateless but they could also be provisioned against whatever type of compute you'd like. Initially we're imagining using kubernetes for this. For now this PoC can be considered closed and a new worker_manager PoC will be started.
