### ISSUE TITLE
[Builder UI] Add unique identifiers to buttons

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#62]
@ryankeairns commented on [Mon Oct 16 2017](https://github.com/habitat-sh/habitat/issues/3792)

As a Habitat team member, 
I would like to capture data that helps me determine where users tend to get stuck
so that I can improve the experience of getting started with Habitat.

With analytics tools, we can track key events to find both challenging flows that make it difficult for users to see immediate value from Habitat. In order to target specific events, it would be helpful if buttons were uniquely identifiable through and `id` parameter and/or unique class name.

Currently, several buttons do not use either which makes them difficult to discern from one another in our data analysis.

- [ ] Add a unique `id` or `class` parameter to all buttons in the Builder UI

List of buttons:
- Sign in with Github
- Connect a plan
- Next (to step 2 of connect a plan file)
- Save connection
- Create an origin
- Generate key pair
- Add Docker Hub account
- Build latest version
- Send invitation

**Comment by cnunciato** [comment]
@apriofrost Is this still needed? I only ask because we seem to have been getting along with our existing setup and instrumentation.

**Comment by nellshamrell** [comment]
Closing this for now, but @apriofrost please feel free to re-open if this is still needed :)

**Comment by apriofrost** [comment]
@cnunciato @nellshamrell We get along with the current setup by limiting and matching the text label on the button in the analytical tool. That means if we update the label of the button, the tracking mechanism will be broken. 
So it will be ideal to have an `id` or `class` for the button implemented in the code so that a text label update won't impact the tracking. But it is not critical at this moment.
