### ISSUE TITLE
Habitat CI + Builder Hooks

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/builder#845]
Currently builder supports only github for triggering `rebuild world` on changes. It also implements its own job server and workers. But `on-prem` installation lacks of this functionality.
We're usually using own git-servers (or even not git vcs at all), own CI: jenkins, drone, gitlab-ci, concourse, etc while going on-prem.

Rebuilding world when dependency has changed - is a killer feature.
I see that builder is way too young: jobsrv and workers aren't available on-prem. 

For me it is not clear about future plans: will jobsrv+worker be available on prem?
Will you add support for most popular on-prem vcs services (like gitlab)?

I understand, there are a lot of work, but as workaround/temporary solution adding `builder hooks` or `events stream api` might work. Why to invent `jobsrv+worker` wheel, while there are so many CI systems? Isn't better to integrate?

**Comment by chefsalim** [comment]
We will be discussing how we move Builder capabilities forward to on-prem, leaving in backlog for discussion

**Comment by eeyun** [comment]
> Why to invent jobsrv+worker wheel, while there are so many CI systems? Isn't better to integrate?

I can add a bit of context to this primarily there are some guarantee's we need to be able to make for our core-plans packages around determinism that would have obligated just as much (if not more) work to fully implement inside CI tools. We've had a vision for builder as being an API that people could tap within their CI/CD pipelines for things like executing tests or validating builds while handling all of the complexity of the deterministic graph so that users don't have to even think about it. In the future, who knows what this will look like. We did initially want to allow for a sort of BYOInfra for on-premises builds. Right now we're discussing what that future state should look like! So, feel free to leave some thoughts on this issue.

> For me it is not clear about future plans: will jobsrv+worker be available on prem?

Initially we had planned to allow users a way to build on prem and connect their on-prem depot to get notifications on core-plans updates from public builder. We aren't 100% that this is what we will end up building but we are discussing it.

> Will you add support for most popular on-prem vcs services (like gitlab)?

A majority of 2018 has been spent refactoring the builder services/logic to get them to a point of AAA stability. Because of that some of our planned feature work has slipped through the cracks. Now that builder is in a much more stable and useful state than it was a year ago we are discussing what the path forward looks like. I personally would love to support integration with gitlab and some of our initially planned changes would have unlocked that work. So while that work isn't currently underway, it is still on the table as we prioritize our efforts for 2019. 

Hopefully this is helpful and feel free to leave your thoughts on this thread!

**Comment by jsirex** [comment]
Actually I see here two possible useful features:
1. Add builder hooks: package uploaded/deleted/promoted/demoted, dependency changed. Hooks, probably, can be configured per-package or per origin with printf-like patterns (example: POST http://service.local/notify/%pkg_origin/%pkg_name/%pkg_channel). This gives us to cover wide number of edge cases.
2. Add git/gitlab support

**Comment by bixu** [comment]
Adding my "pretty please" here for some ability to have a Builder build trigger a build in CircleCI or some similar service. This would unlock all kinds of goodness for my workflows at $job.
