### ISSUE TITLE
Habitat built packages without the Supervisor

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#88]
@coderanger commented on [Wed Dec 20 2017](https://github.com/habitat-sh/habitat/issues/4368)

Opening this to start a discussion, so consider this idea a bit nebulous so far. Basically I love hab studio, but as a k8s user I don't have a ton of need for hab-sup. Being able to build plain ol' images without the Habitat runtime would be a very nice alternative to `docker build`. I could certainly just use things as-is and ignore hab-sup, but it would be nice to not have the extra moving piece. This would mean a few Habitat plan features (like run-time templating) wouldn't work, but it's still a big leg up over `docker build`.

---

@eeyun commented on [Tue Jan 02 2018](https://github.com/habitat-sh/habitat/issues/4368#issuecomment-354845132)

This something we've had a bunch of conversations about over the last year. I think the general feeling on it most recently is that we'd prefer not to do something like that - BUT, thats not a 100% consensus across the community/core-team and I think a feature like this is something that others have also asked about so we ABSOLUTELY should discuss it further with the wider community.

I've updated the issue to include an RFC label and will post about it in the #announcements channel after this week's triage! 

Thank you for opening this issue @coderanger!

---

@bdangit commented on [Tue Jan 02 2018](https://github.com/habitat-sh/habitat/issues/4368#issuecomment-354930917)

Other things that the user may forgo is the ability to expose a health check via port 9631 (which I thought was a nice feature for `k8s` users), a process that tries its best to keep the processes spawned from it up and other nice runtime hooks for managing application health. 

Of course those features are nice when running and maintaining a service. 

In a lot of my use-cases, we use hab to help us build and contain our application.  We value the dependency management and isolation features. When we do run our applications which are really just command line tools, we just use `hab pkg binlink` and then we can use our tool as desired on any Linux machine. Thinking forward a bit we can easily export Docker containers so we can then run our tooling in any Docker machine whether on Linux or Windows.  In these cases, we don’t need to bloat our images with `hab-sup`.

Perhaps in the case where it is really desired not to have these, then we should allow the community to make a `hab-sup`-less exporter.  Or some how offer a `hab-sup` stub.

---

@coderanger commented on [Tue Jan 02 2018](https://github.com/habitat-sh/habitat/issues/4368#issuecomment-354931075)

Kubernetes already has strong restart-on-fail management and health check systems, so Habitat implementing those gets me very little.

**Comment by adamhjk** [comment]
I'm just not sure what this actually buys you. If all you do is run the supervisor as pid 1 of your container, but don't use any of the other features, you get precisely what you want with minimal overhead. Why wouldn't that be sufficient?

**Comment by coderanger** [comment]
It's not minimal if we could reduce it :) It's certainly not egregious overhead, but it is one more moving piece and it would be nice for people that don't really want the runtime features and are just looking at Studio as an image build system.

**Comment by adamhjk** [comment]
The deal is that the supervisor *does* support a bunch of run time things for the services. For example, environment injection, reconfiguration. If habitat supports this as a first party thing, we'll wind up in a situation where folks want those features to work without a supervisor, or where the desire to run a given package "supervisorless" becomes a thing. I wouldn't intentionally make it so you can't just run your software without the supervisor (which, hey, you could now - just run it directly), but I'm a pretty strong -1 on having this be a supported way of running habitat applications.

**Comment by coderanger** [comment]
Yes, I am aware the Supervisor process does a ton of stuff, but the flip side is a lot of those features are redundant with Kubernetes. For example, Kubernetes has its own way to set environment variables in the container. It is not the end of the world to say "well just don't use one or the other" but it would make for a smoother k8s UX to not have to have that conversation every time.

**Comment by adamhjk** [comment]
I'm not talking about user set environment variables - sometimes it's *runtime* environment that makes the packages themselves work. Saying "this package just works in one environment, but completely fails in another" is very much against the purpose of Habitat (which is that everything the application needs can be provided in a way that is agnostic of infrastructure.)

If you look at the k8s operator (https://github.com/kinvolk/habitat-operator/tree/master/examples), a bunch of these use cases are already there. Removing the supervisor from the mix doesn't smooth the UX for k8s out, it just makes it a matrix of behavior instead of a consistent interface.

**Comment by coderanger** [comment]
The operator is a great tool for people that want to use Hab and K8s together, I think the deeper thing I'm asking for is the ability to use Hab Studio without the rest of Habitat. To replace `docker build`, but otherwise produce images that know nothing of hab.

**Comment by tashimi** [comment]
Just fyi, the Habitat Operator now lives in the Habitat repo: https://github.com/habitat-sh/habitat-operator

**Comment by tashimi** [comment]
I had a long and great conversation about this today, and I think this request comes from opaqueness about how Habitat (the ecosystem) is working with Kubernetes via the Operator to give you the application behavior you want, using Kubernetes native communication via the k8s Control Plane. So we're using Operators, adding Stateful Set support, communicating within the cluster using the controller api model, and doing k8s native networking work (no direct sup-to-sup ip addressing from the docker container, e.g.). There are no tasks the Supervisor is trying to control, when they are better served by the capabilities of Kubernetes. This is part of the vision at the heart of Habitat, which is that an application has behaviors and patterns and update strategies and topologies and scaling capabilities that should be bundled and shipped with the application and service itself as intelligent behavior - and then providing the abstractions and complimentary runtime automation to ensure that those behaviors happen in the best possible pattern, wherever you deploy & run them. 

So the behavior of the Supervisor itself as an entity in Kubernetes is very different than the behavior of the Supervisor managing the same workload or services on a VM or baremetal, but the behavior of the application is consistent, and the surrounding automation seeks to use what is available to it in each deployment scenario to the maximum benefit possible to ensure that consistent and reliable and scaleable behavior. At build time you just focus on the behavior of the service that you are building, and then at run time we make sure it runs very well where you deploy it.

**Comment by coderanger** [comment]
Again while I appreciate that is part of the deep vision of Habitat, I would counter that the world view of K8s where the deployment and control stuffs don't live with the app is substantially more popular and it would be nice to be able to use some of the tools without having to take all of them as re-orienting an infrastructure to the world view that Habitat uses can be very difficult. Making it a more modular system allows doing that in phases rather than all at once. This in turn benefits both sides (hab as a project gets more users, users can use just the studio without having to go all-in on hab).

Again the operator is a great tool if you want to use Habitat, but I kind of don't, I just want to use part of it. It's cool to say "no" to that, or at least is within your purview as a project :)

**Comment by tashimi** [comment]
@coderanger this might be off topic (i.e. "How I want to build with Studio") versus "I want an exporter with no supervisor" for this thread, but If you're doing all the builds with reverse dependencies & hab packages and exporting to a container, the additional step of deploying an Operator for k8s seems pretty minimal overhead to get the rest of the way there.  And if you don't want to do any of the service definition using Habitat concepts (i.e. application lifecycle hooks), but instead define and run those in k8s, you can do that. The Operator doesn't fight with the control plane in the cluster, it let's you chose to use `kubectl` and other commands and keeps things in sync.

**Comment by coderanger** [comment]
Yep, I absolutely can do that but it isn't "minimal overhead", it's just very low overhead. The issue is more conceptual, it's hard to get a team on board with this plan because Hab is pitched as this overarching solution (which to be fair, it is :) but since there is a lot of feature overlap between the Hab view of the world and K8s view of the world, it leads to friction from folks that don't know both sides as deeply. The Operator is a great step forward for people coming from the Hab side and saying "okay, now lets keep this party rolling into k8s", but if you come from the k8s side (or just plain Docker but k8s is the driving force of your next infra iteration, which I think is a situation a ton of people are in) then things are a lot less clear.
