### ISSUE TITLE
.bldr.toml should allow users to auto-promote to channels other than unstable

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/builder#99]
@tashimi commented on [Sat Dec 16 2017](https://github.com/habitat-sh/habitat/issues/4328)

This is expected/documented behavior but apparently doesn't exist in the code base. 

## Additional channel promotion

-You can specify a list of additional channels that packages should automatically publish to. By default, software is only published to the `unstable` channel.

-```toml
-# .bldr.toml
-[hab-launcher]
-channels = ["stable"]
-```

---

@tashimi commented on [Sat Dec 16 2017](https://github.com/habitat-sh/habitat/issues/4328#issuecomment-352226242)

- add behavior
- re-add docs removed in #4327

**Comment by smartb-pair** [comment]
@tashimi / @elliott-davis, as of today this has become production-critical for us (had a minor production outage because of the "Polka Problem" described [here](https://forums.habitat.sh/t/the-polka-problem-how-to-build-against-the-latest-version-of-my-orgs-packages-rather-than-those-in-the-stable-channel/488/6), which we think can be circumvented by auto-promoting our origin's packages to a `staging` channel or similar and then setting `HAB_BLDR_CHANNEL` to `staging` in our Builder secrets.

cc: @bixu

**Comment by smartb-pair** [comment]
(It seems at the moment that our only alternative is to stop using Builder entirely and retain only the artifact storage (Depot) functionality.)

**Comment by raskchanky** [comment]
I did some research yesterday into what it would take to enable this feature and it doesn't look that bad.  It looks like it was at least partially implemented at some point in the past, because the `.bldr.toml` file has support in it for channels.  @chefsalim mentioned that he removed parts of this feature at one point, but I'm not clear what the reasons were for that, or if there's something preventing us from putting it back together.

**Comment by rsertelon** [comment]
My 2cts here:

* autopromote should happen when the whole group is built correctly (at least in the origin that triggered the build)
* I'd say no, the risk here is that we'd risk inconsistent deps for hab users
* static would be enough IMHO, for now at least. provided we can easily change while being retro-compatible
* I'd say single channel for now, provided we could change this later while being retro-compatible
* stable has a strong meaning, I think it would be best not to allow it, this should be done explicitly IMHO
* that would be super cool, first thing could be to run builds with DO_CHECK=1, maybe as an option for autopromote? As for other things, it might depend on @eeyun and @nellshamrell work on tests for core plans
* +1

**Comment by raskchanky** [comment]
@rsertelon That's a fair point, and we might also be able to include that as a configuration option inside the `.bldr.toml` file.  Something like `promotion_to_stable_allowed = true`, so it could be tweaked as needed.
